blog
MonalikaPatnaik/UMatter pull request #305
Opened 2023-05-23 18:50 UTC by P766-spec

Added some CSS to blog cards like change the background color , given some round corner to cards , adjust the margin of cards from bottom to have some space between other section.
![Screenshot (583)](https://github.com/MonalikaPatnaik/UMatter/assets/90417642/5b1564df-4a11-4c58-bd92-1f7606c12582)
![Screenshot (584)](https://github.com/MonalikaPatnaik/UMatter/assets/90417642/c5fdbcc9-2f70-4193-b497-20615c7ca7f5)

2023-05-24 03:09 UTC, shivam-sharma7 requested changes

2023-05-24 03:09 UTC, shivam-sharma7 commented on src/Components/Signin/index.js
>  import { NavLink } from "react-router-dom";
```suggestion

import { NavLink } from "react-router-dom";
```

remove extra line for code format

2023-05-25 15:14 UTC, MonalikaPatnaik commented
Could you add the issue link?

2023-05-26 06:36 UTC, MonalikaPatnaik commented
fixes #262

2023-05-26 06:36 UTC, merged